# These cases never start capture or connect to a receiver.
function(check_case expected pattern)
  execute_process(COMMAND "${APP}" --cli ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
  if(NOT "${result}" STREQUAL "${expected}")
    message(FATAL_ERROR "CLI ${ARGN}: expected ${expected}, got ${result}\n${output}\n${error}")
  endif()
  if(NOT output MATCHES "${pattern}")
    message(FATAL_ERROR "CLI ${ARGN}: missing ${pattern}\n${output}\n${error}")
  endif()
  if(output MATCHES "\"event\":\"(start|streaming)\"")
    message(FATAL_ERROR "A non-transmission case reached the live path: ${output}")
  endif()
endfunction()
check_case(0 "--device" --help)
check_case(2 "Unknown option" --unknown)
check_case(2 "device UID is required")
check_case(2 "Unexpected positional" extraneous)
check_case(2 "cannot be combined" --list-devices --receiver 127.0.0.1)
check_case(1 "Input device UID not found" --device airplayqt-nonexistent-test-device --left 2 --right 2 --receiver 127.0.0.1)
check_case(2 "1..256" --device fake --left 0 --receiver 127.0.0.1)
check_case(2 "1..3600" --device fake --seconds 0 --receiver 127.0.0.1)
check_case(2 "1..3600" --device fake --seconds 3601 --receiver 127.0.0.1)
check_case(2 "1..3600" --device fake --startup-timeout 0 --receiver 127.0.0.1)
check_case(2 "Repeated option" --device fake --seconds 1 --seconds 2 --receiver 127.0.0.1)
check_case(2 "\"event\":\"error\"" --device fake --receiver 127.0.0.1 --receiver 127.0.0.1:7000)
check_case(2 "\"event\":\"error\"" --device fake --receiver 127.0.0.1 --receiver 127.0.0.2 --receiver 127.0.0.3)
check_case(2 "\"event\":\"error\"" --device fake --receiver 224.0.0.1)
check_case(2 "\"event\":\"error\"" --device fake --receiver 127.0.0.1:0)
check_case(1 "Input device UID not found" --device airplayqt-nonexistent-test-device --receiver 127.0.0.1)
message(STATUS "16 CLI argument/failure cases passed without transmission")
