# Parser/configuration failures only: no capture or receiver connections.
function(check_case expected pattern)
  execute_process(COMMAND "${APP}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
  if(NOT "${result}" STREQUAL "${expected}" OR NOT "${output}${error}" MATCHES "${pattern}")
    message(FATAL_ERROR "CLI ${ARGN}: expected ${expected}/${pattern}, got ${result}\n${output}\n${error}")
  endif()
endfunction()
set(config "${CMAKE_CURRENT_BINARY_DIR}/linux-cli-config-v4.json")
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../doc/config.example.json" original)
file(WRITE "${config}" "${original}")
check_case(0 "--config" --help)
check_case(0 "AirPlayQtCli" --version)
check_case(2 "--config PATH is required" --device fake --receiver 127.0.0.1)
check_case(2 "--device is required" --config "${config}")
check_case(2 "--left must be 1 or 2" --config "${config}" --device fake --left 0 --receiver 127.0.0.1)
check_case(2 "Unknown option" --config "${config}" --packet-samples 64)
check_case(2 "Repeated option" --config "${config}" --config "${config}")
check_case(2 "cannot be combined" --list-devices --config "${config}")
check_case(1 "missing-config.json" --config "${CMAKE_CURRENT_BINARY_DIR}/missing-config.json" --device fake --receiver 127.0.0.1)
file(WRITE "${config}" "{broken")
check_case(1 "Corrupt configuration" --config "${config}" --device fake --receiver 127.0.0.1)
string(REPLACE "\"version\": 4" "\"version\": 3" legacy "${original}")
file(WRITE "${config}" "${legacy}")
check_case(1 "Invalid configuration structure or version" --config "${config}" --device fake --receiver 127.0.0.1)
file(READ "${config}" after)
if(NOT after STREQUAL legacy)
  message(FATAL_ERROR "CLI overwrote incompatible configuration")
endif()
string(REPLACE "\"packetSamples\": 64" "\"packetSamples\": 353" invalid "${original}")
file(WRITE "${config}" "${invalid}")
check_case(1 "out of range" --config "${config}" --device fake --receiver 127.0.0.1)
file(WRITE "${config}" "${original}")
