# Shared deployment/audit primitives. All paths are arguments, never shell text.
cmake_minimum_required(VERSION 3.25)
function(mac_run label)
  message(STATUS "${label}: ${ARGN}")
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output
    ERROR_VARIABLE errors TIMEOUT 180)
  file(APPEND "${REPORT}" "\n## ${label}\n${output}${errors}\n")
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "${label} failed (${result}): ${output}${errors}\nSee ${REPORT}")
  endif()
endfunction()

function(mac_binaries root out)
  file(GLOB_RECURSE files LIST_DIRECTORIES FALSE "${root}/*")
  set(binaries)
  foreach(path IN LISTS files)
    if(IS_SYMLINK "${path}")
      if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Broken symlink: ${path}")
      endif()
      continue()
    endif()
    file(READ "${path}" magic LIMIT 4 HEX)
    if(magic MATCHES "^(cffaedfe|cefaedfe|feedfacf|feedface|cafebabe|bebafeca|cafebabf|bfbafeca)$")
      list(APPEND binaries "${path}")
    endif()
  endforeach()
  set(${out} "${binaries}" PARENT_SCOPE)
endfunction()

function(mac_dependencies binary out)
  execute_process(COMMAND /usr/bin/otool -L "${binary}" OUTPUT_VARIABLE output
    COMMAND_ERROR_IS_FATAL ANY)
  string(REGEX MATCHALL "\n\t[^\n]+" lines "${output}")
  set(dependencies)
  foreach(line IN LISTS lines)
    string(REGEX REPLACE "^\n\t(.*) \\(compatibility version.*$" "\\1" path "${line}")
    list(APPEND dependencies "${path}")
  endforeach()
  # otool -L includes LC_ID_DYLIB; it is an identity, not a load dependency.
  execute_process(COMMAND /usr/bin/otool -D "${binary}" OUTPUT_VARIABLE identity
    COMMAND_ERROR_IS_FATAL ANY)
  string(REPLACE "\n" ";" identity_lines "${identity}")
  list(LENGTH identity_lines identity_count)
  if(identity_count GREATER 1)
    list(GET identity_lines 1 identity)
    string(STRIP "${identity}" identity)
    list(REMOVE_ITEM dependencies "${identity}")
  endif()
  set(${out} "${dependencies}" PARENT_SCOPE)
endfunction()

function(mac_library_key path out)
  if(path MATCHES "([^/]+\\.framework/.*)$")
    set(key "${CMAKE_MATCH_1}")
  else()
    get_filename_component(key "${path}" NAME)
  endif()
  set(${out} "${key}" PARENT_SCOPE)
endfunction()

function(mac_rewrite binary frameworks)
  mac_dependencies("${binary}" dependencies)
  get_filename_component(directory "${binary}" DIRECTORY)
  foreach(dependency IN LISTS dependencies)
    if(dependency MATCHES "^(/System/Library/|/usr/lib/)")
      continue()
    endif()
    mac_library_key("${dependency}" key)
    set(target "${frameworks}/${key}")
    if(NOT EXISTS "${target}")
      message(FATAL_ERROR "Missing dependency ${dependency} for ${binary}: ${target}")
    endif()
    file(RELATIVE_PATH relative "${directory}" "${target}")
    mac_run("Relocate ${binary}" /usr/bin/install_name_tool
      -change "${dependency}" "@loader_path/${relative}" "${binary}")
  endforeach()
  execute_process(COMMAND /usr/bin/otool -l "${binary}" OUTPUT_VARIABLE commands
    COMMAND_ERROR_IS_FATAL ANY)
  string(REGEX MATCHALL "cmd LC_RPATH\n[^\n]*\n[^\n]*" rpaths "${commands}")
  foreach(entry IN LISTS rpaths)
    string(REGEX REPLACE ".*\n *path (.*) \\(offset.*" "\\1" path "${entry}")
    mac_run("Remove build rpath" /usr/bin/install_name_tool -delete_rpath "${path}" "${binary}")
  endforeach()
  if(commands MATCHES "cmd LC_ID_DYLIB")
    mac_library_key("${binary}" key)
    mac_run("Library identity" /usr/bin/install_name_tool -id "@rpath/${key}" "${binary}")
  endif()
endfunction()

function(mac_audit root)
  foreach(required IN ITEMS Contents/MacOS/AirPlayQt Contents/Info.plist
      Contents/PlugIns/platforms/libqcocoa.dylib Contents/Resources/ThirdPartyLicenses/CONTENTS.txt)
    if(NOT EXISTS "${root}/${required}")
      message(FATAL_ERROR "Missing bundle resource: ${root}/${required}")
    endif()
  endforeach()
  file(REAL_PATH "${root}" canonical_root)
  mac_binaries("${root}" binaries)
  if(NOT binaries)
    message(FATAL_ERROR "No Mach-O files in ${root}")
  endif()
  foreach(binary IN LISTS binaries)
    execute_process(COMMAND /usr/bin/lipo -archs "${binary}" OUTPUT_VARIABLE arch
      OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    if(NOT arch STREQUAL "arm64")
      message(FATAL_ERROR "Unexpected architectures ${arch}: ${binary}")
    endif()
    execute_process(COMMAND /usr/bin/otool -l "${binary}" OUTPUT_VARIABLE commands
      COMMAND_ERROR_IS_FATAL ANY)
    if(commands MATCHES "cmd LC_RPATH")
      message(FATAL_ERROR "Unnecessary runtime search path: ${binary}")
    endif()
    if(commands MATCHES "minos ([0-9.]+)" AND CMAKE_MATCH_1 VERSION_GREATER "27.0")
      message(FATAL_ERROR "Dependency needs macOS ${CMAKE_MATCH_1}: ${binary}")
    endif()
    mac_dependencies("${binary}" dependencies)
    get_filename_component(directory "${binary}" DIRECTORY)
    foreach(dependency IN LISTS dependencies)
      if(dependency MATCHES "^(/System/Library/|/usr/lib/)")
        continue()
      endif()
      if(NOT dependency MATCHES "^@loader_path/(.*)$")
        message(FATAL_ERROR "Nonlocal dependency ${dependency} in ${binary}")
      endif()
      set(target "${directory}/${CMAKE_MATCH_1}")
      if(NOT EXISTS "${target}")
        message(FATAL_ERROR "Unresolved dependency: ${target}")
      endif()
      file(REAL_PATH "${target}" canonical)
      cmake_path(IS_PREFIX canonical_root "${canonical}" NORMALIZE inside)
      if(NOT inside)
        message(FATAL_ERROR "Dependency escapes bundle: ${target}")
      endif()
    endforeach()
  endforeach()
  file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE "${root}/*")
  foreach(entry IN LISTS entries)
    if(IS_SYMLINK "${entry}")
      if(NOT EXISTS "${entry}")
        message(FATAL_ERROR "Broken symlink: ${entry}")
      endif()
      file(REAL_PATH "${entry}" canonical)
      cmake_path(IS_PREFIX canonical_root "${canonical}" NORMALIZE inside)
      if(NOT inside)
        message(FATAL_ERROR "Symlink escapes bundle: ${entry}")
      endif()
    endif()
  endforeach()
  list(LENGTH binaries count)
  file(APPEND "${REPORT}" "\nAudit passed: ${root}: ${count} arm64 Mach-O files, closed dependencies.\n")
endfunction()

function(mac_sign root)
  mac_binaries("${root}" binaries)
  foreach(binary IN LISTS binaries)
    mac_run("Sign Mach-O" /usr/bin/codesign --force --sign - --timestamp=none "${binary}")
  endforeach()
  file(GLOB frameworks "${root}/Contents/Frameworks/*.framework")
  foreach(framework IN LISTS frameworks)
    mac_run("Sign framework" /usr/bin/codesign --force --sign - --timestamp=none "${framework}")
  endforeach()
  mac_run("Sign bundle" /usr/bin/codesign --force --sign - --timestamp=none "${root}")
  mac_run("Verify bundle signature" /usr/bin/codesign --verify --deep --strict --verbose=2 "${root}")
endfunction()

function(mac_verify_trace path required)
  file(READ "${path}" trace)
  # Inspect actual dyld loads, not Qt's optional plugin search-path diagnostics.
  string(REGEX MATCHALL "dyld\\[[0-9]+\\]: <[^>]+> /[^\n]+" images "${trace}")
  foreach(image IN LISTS images)
    string(REGEX REPLACE "^dyld\\[[0-9]+\\]: <[^>]+> " "" image "${image}")
    if(image MATCHES "^(/System/Library/|/usr/lib/)")
      continue()
    endif()
    cmake_path(IS_PREFIX required "${image}" NORMALIZE inside)
    if(NOT inside AND NOT image STREQUAL "${ARGN}")
      message(FATAL_ERROR "Image loaded outside the tested bundle: ${image}")
    endif()
  endforeach()
  string(FIND "${trace}" "${required}/Contents/Frameworks/QtCore.framework" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "No evidence of bundled QtCore in ${path}")
  endif()
endfunction()

# Used by negative packaging checks in a fresh CMake process.
if(DEFINED AUDIT_ROOT)
  mac_audit("${AUDIT_ROOT}")
endif()
