# Collect installed notices using the actual resolved dependency provenance.
# Qt's Homebrew bottle omits its license directory, so extract notices from the
# exact upstream source archive pinned by the installed Homebrew formula.
function(mac_licenses dependencies destination)
  set(prefixes)
  foreach(dependency IN LISTS dependencies)
    file(REAL_PATH "${dependency}" original)
    if(NOT original MATCHES "^(/opt/homebrew/Cellar/([^/]+)/[^/]+)/")
      message(FATAL_ERROR "Cannot establish license provenance for ${original}")
    endif()
    list(APPEND prefixes "${CMAKE_MATCH_1}")
  endforeach()
  list(REMOVE_DUPLICATES prefixes)
  file(MAKE_DIRECTORY "${destination}")
  foreach(prefix IN LISTS prefixes)
    get_filename_component(version "${prefix}" NAME)
    get_filename_component(parent "${prefix}" DIRECTORY)
    get_filename_component(name "${parent}" NAME)
    set(output "${destination}/${name}-${version}")
    file(MAKE_DIRECTORY "${output}")
    file(GLOB notices "${prefix}/LICENSE*" "${prefix}/COPYING*" "${prefix}/COPYRIGHT*"
      "${prefix}/AUTHORS*" "${prefix}/NOTICE*" "${prefix}/LICENCE*"
      "${prefix}/LGPL*" "${prefix}/GPL*" "${prefix}/FTL*" "${prefix}/docs/FTL*"
      "${prefix}/docs/GPL*" "${prefix}/share/doc/${name}/LICENSE*")
    if(name STREQUAL "qtbase")
      file(READ "${prefix}/.brew/qtbase.rb" recipe)
      string(REGEX MATCH "\n  url \"([^\"]+)\"" match "${recipe}")
      set(url "${CMAKE_MATCH_1}")
      string(REGEX MATCH "\n  sha256 \"([0-9a-f]+)\"" match "${recipe}")
      set(hash "${CMAKE_MATCH_1}")
      if(NOT url MATCHES "^https://download.qt.io/" OR NOT hash)
        message(FATAL_ERROR "Cannot identify pinned Qt source archive")
      endif()
      set(cache "${BUILD_ROOT}/package-sources/${hash}")
      file(MAKE_DIRECTORY "${cache}")
      set(archive "${cache}/qtbase.tar.xz")
      if(NOT EXISTS "${archive}")
        message(STATUS "Downloading exact Qt license sources: ${url}")
        file(DOWNLOAD "${url}" "${archive}" EXPECTED_HASH "SHA256=${hash}"
          TLS_VERIFY ON STATUS download TIMEOUT 180)
        list(GET download 0 code)
        if(NOT code EQUAL 0)
          file(REMOVE "${archive}")
          message(FATAL_ERROR "Qt source download failed: ${download}")
        endif()
      endif()
      file(SHA256 "${archive}" actual)
      if(NOT actual STREQUAL hash)
        message(FATAL_ERROR "Qt source archive checksum mismatch: ${archive}")
      endif()
      if(NOT EXISTS "${cache}/source/complete")
        file(REMOVE_RECURSE "${cache}/source")
        file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${cache}/source")
        file(WRITE "${cache}/source/complete" "${hash}\n")
      endif()
      file(GLOB roots LIST_DIRECTORIES TRUE "${cache}/source/qtbase-*")
      list(LENGTH roots count)
      if(NOT count EQUAL 1)
        message(FATAL_ERROR "Unexpected Qt source archive structure")
      endif()
      list(GET roots 0 source)
      file(GLOB_RECURSE qt_files LIST_DIRECTORIES FALSE "${source}/*")
      foreach(path IN LISTS qt_files)
        get_filename_component(filename "${path}" NAME)
        string(TOLOWER "${filename}" lower)
        if(lower MATCHES "(licen[sc]e|copying|copyright|notice|qt_attribution.json|^ftl\\.txt$|^gpl\\.txt$)" OR path MATCHES "/LICENSES/")
          file(RELATIVE_PATH relative "${source}" "${path}")
          get_filename_component(directory "${output}/${relative}" DIRECTORY)
          file(MAKE_DIRECTORY "${directory}")
          file(COPY "${path}" DESTINATION "${directory}")
        endif()
      endforeach()
      file(WRITE "${output}/SOURCE.txt" "Qt ${version}\n${url}\nSHA256 ${hash}\nDynamically linked; the packaged Qt libraries may be replaced with ABI-compatible builds.\n")
      file(COPY "${prefix}/share/qt/sbom/qtbase-${QT_VERSION}.spdx" DESTINATION "${output}")
    elseif(NOT notices)
      message(FATAL_ERROR "Missing license notices for ${name} (${prefix})")
    endif()
    if(notices)
      file(COPY ${notices} DESTINATION "${output}")
    endif()
    if(EXISTS "${prefix}/sbom.spdx.json")
      file(COPY "${prefix}/sbom.spdx.json" DESTINATION "${output}")
    endif()
    if(EXISTS "${prefix}/.brew/${name}.rb")
      file(COPY "${prefix}/.brew/${name}.rb" DESTINATION "${output}")
    endif()
    file(APPEND "${destination}/CONTENTS.txt" "${name} ${version}\n")
  endforeach()
  # The matching FreeType sources are included in this Qt source release.
  # Its top-level LICENSE.TXT refers to FTL.TXT, which Homebrew omits.
  file(GLOB freetype_attributions "${destination}/qtbase-*/src/3rdparty/freetype/qt_attribution.json")
  foreach(attribution IN LISTS freetype_attributions)
    file(READ "${attribution}" metadata)
    string(JSON freetype_version GET "${metadata}" 0 Version)
    get_filename_component(directory "${attribution}" DIRECTORY)
    file(GLOB freetype_notices "${directory}/*LICENSE*" "${directory}/docs/FTL.TXT" "${directory}/docs/GPL.TXT")
    if(EXISTS "${destination}/freetype-${freetype_version}")
      file(COPY ${freetype_notices} DESTINATION "${destination}/freetype-${freetype_version}")
      file(WRITE "${destination}/freetype-${freetype_version}/ATTRIBUTION.txt"
        "This software uses the FreeType project (https://freetype.org).\nComplete notices from the matching FreeType ${freetype_version} source included with Qt.\n")
    else()
      message(FATAL_ERROR "FreeType license source version differs from installed runtime")
    endif()
  endforeach()
endfunction()
