cmake_minimum_required(VERSION 3.25)
get_filename_component(source "${PLUGIN}" DIRECTORY)
set(directory "${TEST_ROOT}/${SCENARIO}")
if(SCENARIO STREQUAL "unicode")
  string(APPEND directory "/中文 插件目录")
endif()
file(MAKE_DIRECTORY "${directory}")
file(COPY "${PLUGIN}" "${source}/runtime" DESTINATION "${directory}")
set(mode normal)
if(SCENARIO STREQUAL "relocate")
  set(mode relocate)
endif()
set(preload "")
if(SCENARIO STREQUAL "missing-engine")
  file(REMOVE "${directory}/runtime/AirPlayQtEngine.dll")
  set(mode failure)
elseif(SCENARIO STREQUAL "missing-dependency")
  file(REMOVE "${directory}/runtime/libplist-2.0.dll")
  set(mode failure)
elseif(SCENARIO STREQUAL "missing-platform")
  file(REMOVE "${directory}/runtime/platforms/qwindows.dll")
  set(mode failure)
elseif(SCENARIO STREQUAL "wrong-entry")
  file(COPY_FILE "${FAKE}" "${directory}/runtime/AirPlayQtEngine.dll")
  file(SHA256 "${FAKE}" hash)
  file(READ "${directory}/runtime/runtime-sha256.txt" manifest)
  string(REGEX REPLACE "[0-9a-f]+  AirPlayQtEngine.dll" "${hash}  AirPlayQtEngine.dll" manifest "${manifest}")
  file(WRITE "${directory}/runtime/runtime-sha256.txt" "${manifest}")
  set(mode failure)
elseif(SCENARIO STREQUAL "conflict")
  set(preload "${directory}/Qt6Core.dll")
  file(COPY_FILE "${FAKE}" "${preload}")
  set(mode failure)
elseif(SCENARIO STREQUAL "identical")
  set(preload "${directory}/libplist-2.0.dll")
  file(COPY_FILE "${directory}/runtime/libplist-2.0.dll" "${preload}")
endif()
execute_process(COMMAND "${HOST}" "${directory}/AirPlayQt.vst3" "${mode}" ${preload}
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 75)
file(WRITE "${directory}/result.txt" "${output}\n${error}\nexit=${result}\n")
message(STATUS "${output}${error}")
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "Native scenario ${SCENARIO} failed: ${result}")
endif()
